### ISSUE TITLE
Request for Access to AlignRE Code or Dataset

### ISSUE THREAD

**Issue by Cishenn** [lizehan1999/AlignRE#1]
Hello Zehan Li, Fu Zhang, and Jingwei Cheng,

I hope this message finds you well. My name is Faiz Li, and I am a researcher from the School of Software at Southeast University, China. I am reaching out to express my keen interest in your recent publication titled "AlignRE: An Encoding and Semantic Alignment Approach for Zero-Shot Relation Extraction," which was featured in ACL 2024 Findings.

Your work presents an innovative approach to zero-shot relation extraction, and I believe it could significantly benefit my current research endeavors. I am particularly intrigued by the AlignRE model and the semantic alignment strategy you've developed.

As I am eager to explore the practical implications of your findings and potentially integrate them into my work, I am writing to kindly request access to the codebase for AlignRE. If the code is not yet ready for public release, I would be grateful for any updates on its anticipated release timeline.

In the meantime, should you be able to share the dataset used in your study, it would greatly facilitate the initiation of my experiments and allow me to provide constructive feedback at an early stage.

I understand the effort that goes into making research materials publicly accessible and appreciate any information you can provide regarding the availability of your code or data. Your contribution to open science is invaluable, and I am looking forward to the opportunity to contribute to the ongoing dialogue within our research community.

Thank you for considering my request. I am looking forward to your response and the possibility of further collaboration.

Best regards,

Faiz Li
School of Software, Southeast University, China
[faizli@tencent.com](mailto:faizli@seu.edu) 
[lichuang@seu.edu.cn](mailto:lichuang@seu.edu.cn)

**Comment by ZiJieNi** [comment]
有同样问题

**Comment by yanghanlin** [comment]
+1 Same question here.
